### ISSUE TITLE
vue-loading with vue-router / router-view

### ISSUE THREAD

**Issue by ChristopherDosin** [Coffcer/vue-loading#1]
I have a question. I am using the vue-router and want to use your `vue-loading` everytime a new component is loaded.

Therefore this is my `app.vue`

```
<template>
    <div class="container">
        <sidebar></sidebar>
        <div v-loading="loading">
            <router-view></router-view>
        </div>
    </div>
</template>

<script>
    import sidebar from './components/main-wrapper/sidebar/index.vue';
    import loading from 'vue-loading';
    export default {
        components: { sidebar },
        directives: { loading }
    };
</script>
```

In my sidebar/index.vue i have all my links e.g

```
<a v-loading="loading" v-link="{ path: '/home/foo' }">Foo</a>
```

Now if i click the Link, the component should be loaded with your `vue-loading`. But nothing appears. In my Dev Console i get only `undefined`. Could you tell me what i am doing wrong?

**Comment by Coffcer** [comment]
Sorry, my English not good, I think you need to 

``` javascript
export default {
        components: { sidebar },
        directives: { loading },
        data () {
            return { loading: false   }
        }
    };
```

``` html
<a @click="loading = true" v-link="{ path: '/home/foo' }">Foo</a>
```

Now if you click the link, the component should be loaded. And then you need to set `loading = false` after `vue-router` redirect.
I will write clearly in README.MD tomorrow.
